# Sample workflow for scanning a target with Snyk API & Web
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab  workflow_dispatch:
jobs:

scan:
   runs-on: ubuntu-latest
   steps:
      - name: Scan with Snyk API & Web
        id: snyk-scan
        uses: Probely/probely-github-action@main
        with:
         api-key: ${{ secrets.PROBLEY_KEY }}
         target-id: "2DmEAb82BHJF"
         region: "eu"
